# Generated by Django 3.0.2 on 2020-04-01 15:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Name', models.CharField(help_text='Name of the Patient', max_length=200)),
                ('Identity Document Number', models.CharField(help_text='Identity Document Number', max_length=10)),
                ('Date of Birth', models.DateField(blank=True, null=True)),
                ('Date Case Confirmed', models.DateField(default=datetime.date.today)),
                ('Case Number', models.IntegerField(default=0, help_text='The case number of the Patient', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location Visited', models.CharField(help_text='Name of the Location', max_length=200)),
                ('Address', models.CharField(blank=True, help_text='Address of the Location', max_length=200, null=True)),
                ('District', models.CharField(help_text='District of the Location', max_length=200)),
                ('X Coord', models.FloatField(help_text='X Coordiates of the location')),
                ('Y Coord', models.FloatField(help_text='Y Coordiates of the location')),
                ('Date From', models.DateField(default=datetime.date.today)),
                ('Date To', models.DateField(default=datetime.date.today)),
                ('Detail', models.CharField(blank=True, max_length=65536, null=True)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trans19.Patient')),
            ],
        ),
    ]
