# Generated by Django 3.0.2 on 2020-04-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelhistory',
            name='X Coord',
            field=models.FloatField(help_text='X Coordiates/Longitude of the location'),
        ),
        migrations.AlterField(
            model_name='travelhistory',
            name='Y Coord',
            field=models.FloatField(help_text='Y Coordiates/Latitude of the location'),
        ),
    ]
