# Generated by Django 3.0.2 on 2020-04-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0002_auto_20200402_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Case Number',
            field=models.IntegerField(help_text='The case number of the Patient', primary_key=True, serialize=False),
        ),
    ]
