# Generated by Django 3.0.2 on 2020-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0004_auto_20200406_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the Location', max_length=200, verbose_name='Location Category')),
            ],
        ),
    ]
