# Generated by Django 3.0.2 on 2020-04-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.AddField(
            model_name='travelhistory',
            name='Category',
            field=models.CharField(choices=[('r', 'Residence'), ('w', 'Workplace'), ('v', 'Visit'), ('s', 'School')], default='v', max_length=1, verbose_name='Category'),
        ),
    ]
