# Generated by Django 3.0.2 on 2020-04-28 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0007_remove_travelhistory_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trans19.TravelHistory'),
        ),
    ]
