# Generated by Django 3.0.2 on 2020-04-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans19', '0008_patient_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Visited', models.CharField(blank=True, help_text='Name of the Location', max_length=200, verbose_name='Location Visited')),
                ('Address', models.CharField(blank=True, help_text='Address of the Location', max_length=200, null=True, verbose_name='Address')),
                ('District', models.CharField(help_text='District of the Location', max_length=200, verbose_name='District')),
                ('XCoord', models.FloatField(default=0, help_text='X Coordiates/Longitude of the location', verbose_name='X Coord')),
                ('YCoord', models.FloatField(default=0, help_text='Y Coordiates/Latitude of the location', verbose_name='Y Coord')),
            ],
        ),
    ]
